apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-secondary
  namespace: guestbook
spec:
  selector:
    matchLabels:
      app: redis
      role: secondary
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: secondary
        tier: backend
    spec:
      containers:
      - name: secondary
        image: gcr.io/google-samples/gb-redis-secondary:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: REDIS_MASTER_SERVICE_HOST
          value: redis-primary.guestbook.svc.clusterset.local
        ports:
        - containerPort: 6379
